# Generated by Django 6.0.2 on 2026-02-14 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('most_famous_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='famous_era', to='paintings.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='paintings.era'),
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year_created', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_co_author', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('co_authors', models.ManyToManyField(blank=True, related_name='paintings', to='paintings.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='famous_painting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_artist', to='paintings.painting'),
        ),
    ]
