# Generated by Django 6.0.2 on 2026-02-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
