# Generated by Django 6.0.2 on 2026-02-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_painting_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='main_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_paintings', to='paintings.artist'),
        ),
    ]
