# Generated by Django 6.0.2 on 2026-02-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_painting_main_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('interes', models.BooleanField(default=False)),
                ('count', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='era',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='famous_painting',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='main_author',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='co_authors',
        ),
        migrations.CreateModel(
            name='RedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('lastes_plant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastes_plant_redbook', to='paintings.plants')),
            ],
        ),
        migrations.AddField(
            model_name='plants',
            name='red_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redBook', to='paintings.redbook'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region_plants', models.ManyToManyField(blank=True, related_name='plants_regions', to='paintings.plants')),
                ('region_redbook', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redbook_region', to='paintings.redbook')),
            ],
        ),
        migrations.DeleteModel(
            name='Era',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Painting',
        ),
    ]
