# Generated by Django 6.0.2 on 2026-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_plants_remove_artist_era_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redbook',
            name='interes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='interes',
            field=models.BooleanField(default=False),
        ),
    ]
