# Generated by Django 6.0.2 on 2026-03-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_redbook_interes_region_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zakon_sbornik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakon_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('original_link', models.URLField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='redbook',
            name='lastes_plant',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_plants',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region_redbook',
        ),
        migrations.DeleteModel(
            name='Plants',
        ),
        migrations.DeleteModel(
            name='RedBook',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
