# Generated by Django 6.0.2 on 2026-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_user_zakon_sbornik_remove_redbook_lastes_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_laws',
            field=models.ManyToManyField(blank=True, to='paintings.zakon_sbornik'),
        ),
    ]
