# Generated by Django 6.0.2 on 2026-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_user_favorite_laws'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
