# Generated by Django 6.0.2 on 2026-03-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0009_user_is_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTVET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('answer', models.TextField()),
                ('laws', models.ManyToManyField(blank=True, to='paintings.zakon_sbornik')),
            ],
        ),
        migrations.CreateModel(
            name='OTVET_REQUEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paintings.otvet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.user')),
            ],
        ),
    ]
