# Generated by Django 6.0.2 on 2026-03-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0010_otvet_otvet_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='otvet_request',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
    ]
