# Generated by Django 6.0.2 on 2026-03-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0011_otvet_request_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paintings.user')),
                ('zakon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.zakon_sbornik')),
            ],
        ),
    ]
